openapi: 3.0.2
info:
  title: Comments resources
  version: 1.0.0
paths: {}
components:
  schemas:
    create–°ommentRequest:
      type: object

      properties:
        rating:
          type: integer
          format: int32
          maximum: 1
          minimum: 5
          example: 4

        content:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        publicDate:
          type: string
          format: Date
          example: 2023-01-08T06:24:40.283Z

        offerId:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        userId:
          type: string
          example: 6329c3d6a04ab1061c6425ea

    commentResponse:
      type: object

      properties:
        rating:
          type: integer
          format: int32
          maximum: 1
          minimum: 5
          example: 4

        content:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        publicDate:
          type: string
          format: Date
          example: 2023-01-08T06:24:40.283Z

        user:
          type: object
          properties:
            schema:
              $ref: './user.resources.yml#/components/schemas/userResponse'
