openapi: 3.0.2
info:
  title: User resources
  version: 1.0.0
paths: {}
components:
  schemas:
    createUserRequest:
      type: object

      properties:
        email:
          type: string
          example: keks@htmlacademy.ru

        name:
          type: string
          example: Keks

        type:
          type: string
          example: Pro
          enum:
            - Ordinary
            - Pro

        password:
          type: string
          example: 123456

    loginUserRequest:
      type: object

      properties:
        password:
          type: string
          example: 123456

        email:
          type: string
          example: mail@example.com

    updateUserRequest:
      type: object

      properties:
        name?:
          type: string
          example: Клод Моне

        avatar?:
          type: string
          example: avatar.jpg

        type?:
          type: string
          enum:
            - Pro
            - Ordinary
          example: Pro

        favoriteOffersId:
          type: array
          example: ['666f5c9294cdd4c101970b17', '446f5c9294cdgtc101970b87']

    userResponse:
      type: object

      properties:
        email:
          type: string
          example: keks@htmlacademy.ru

        name:
          type: string
          example: Keks

        type:
          type: string
          example: Pro
          enum:
            - Ordinary
            - Pro

        avatar:
          type: string
          example: avatar.jpg

        id:
          type: string
          example: 666f5c9294cdd4c101970b17

        favoriteOffersId:
          type: array
          example: ['666f5c9294cdd4c101970b17', '446f5c9294cdgtc101970b87']

    uploadAvatarResponse:
      type: object

      properties:
        avatar:
          type: string
          example: avatar.jpg

